### ISSUE TITLE
Correct MiXCR commands

### ISSUE THREAD

**Issue by PoslavskySV** [smangul1/imrep.GTEx#1]
Dear colleagues, 

I just have noticed that the commands used for running MiXCR are slightly incorrect, which may cause an observable loss of number of output clonotypes. In particular there are three issues:

 - it is required to use `-OallowPartialAlignments=true` parameter when running MiXCR `align` on RNA-Seq data
 - it is generally recommended to use the `extendAlignments` action to rescue some of T-cell CDR3s (does not affect IG)
- also, if you use MiXCR for comparison with software that does not account for sequence quality score, you need to turn off this kind of filtering in MiXCR `assemble` with `-ObadQualityThreshold=0` (see [this doc](http://mixcr.readthedocs.io/en/latest/assemble.html#assembler-parameters) for details)

This is documented at the [MiXCR documentation page](http://mixcr.readthedocs.io/en/latest/rnaseq.html#typical-analysis-workflow) and additionally you can find a more detailed explanation in our recent MiXCR paper (Nat.Bio. 35, 908–911 (2017)).

The correct commands to run MiXCR are:

```
mixcr align -p rna-seq -OallowPartialAlignments=true -r log_align.txt $1 $2 alignments.vdjca
mixcr assemblePartial -p alignments.vdjca alignments_rescued_1.vdjca 
mixcr assemblePartial alignments_rescued_1.vdjca alignments_rescued_2.vdjca
mixcr extendAlignments alignments_rescued_2.vdjca alignments_rescued_2_extended.vdjca
mixcr assemble -r log_assemble.txt -ObadQualityThreshold=0 alignments_rescued_2_extended.vdjca mixcr.clns
mixcr exportClones mixcr.clns mixcr.txt
```

Also it is always recommended to use release version of MiXCR ([2.1.3](http://doi.org/10.5281/zenodo.804046) was released with Nat.Bio paper; the current latest is [2.1.9](https://doi.org/10.5281/zenodo.593514)), since the snapshot versions may contain some unstable things.

PS: thanks for doing high quality, transparent and reproducible analysis with different software (this is something one can't see very often in biology:-)) !

With best wishes,
Stanislav

**Comment by smangul1** [comment]
Thanks for letting me know. We will try to rerun mixcr. We will share the script with you 

Serghei

**Comment by smangul1** [comment]
We have modified the MiXCR script based on your suggestions: https://github.com/smangul1/imrep.GTEx/blob/master/code/run.mixcr.sh

Thanks, 
Serghei
